apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-flask-app
  labels:
    app: k8-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-flask-app
  template:
    metadata:
      labels:
        app: k8-flask-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: k8-flask-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5001
